/**
 * Shared token-replacement renderer for `EmailTemplate`/`Email` content
 * (docs/plans/08-email-templates.md § Domain concepts) — reused as-is by
 * `09-emails.md` (preview) and later by `12-campaign-engine.md` (real send).
 *
 * Deliberately NOT a full templating engine: no conditionals/loops, just a
 * regex pass over known `{{ namespace.field }}` tokens. This keeps the
 * content-authoring surface free of any code-execution risk.
 */
export interface VariableContext {
  contact: {
    firstname: string
    lastname: string
    email: string
    phone: string
    company: string
    country: string
    city: string
    language: string
    timezone: string
  }
  project: {
    name: string
  }
  subject: string
  /**
   * System-generated by docs/plans/17-unsubscribe.md, never a stored value —
   * the one token that is a URL rather than free text, so it must NEVER be
   * HTML-escaped (escaping would break the href / percent-encode the URL).
   */
  unsubscribeUrl: string
}

const TOKEN_PATTERN = /\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g

const HTML_ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => HTML_ESCAPES[char])
}

function resolveToken(token: string, context: VariableContext): string | undefined {
  if (token === 'unsubscribe_url') return context.unsubscribeUrl
  if (token === 'project.name') return context.project.name
  if (token === 'subject') return context.subject

  const contactField = token.match(/^contact\.([a-zA-Z0-9_]+)$/)?.[1]
  if (contactField) {
    return (context.contact as Record<string, string>)[contactField]
  }

  return undefined
}

/**
 * Replaces every known `{{ token }}` in `content` with its resolved value —
 * HTML-escaped unless `escape` is false. A token that doesn't resolve to
 * anything (unknown namespace, misspelled field, ...) is left in the output
 * exactly as written — this is the intentional, user-facing way to spot a
 * typo'd variable (docs/plans/08-email-templates.md § Edge cases), not a
 * silent removal or a hard error.
 */
function render(content: string, context: VariableContext, escape: boolean): string {
  return content.replace(TOKEN_PATTERN, (match, token: string) => {
    const value = resolveToken(token, context)
    if (value === undefined) return match

    return escape && token !== 'unsubscribe_url' ? escapeHtml(value) : value
  })
}

/** For HTML content — see `render()`. Escapes every value (XSS defense) except `unsubscribe_url`. */
export function renderVariables(content: string, context: VariableContext): string {
  return render(content, context, true)
}

/**
 * For plain-text content (`Email`/`EmailTemplate`/`EmailLayout` `textContent`)
 * — see `render()`. Never HTML-escapes: unlike HTML, plain text has no markup
 * to guard against, so escaping would just corrupt a contact field containing
 * `&`, `<`, `'`, etc. into literal entities in the sent text (e.g. a company
 * named "Smith & Sons" would otherwise read "Smith &amp; Sons").
 */
export function renderTextVariables(content: string, context: VariableContext): string {
  return render(content, context, false)
}

/** Example values used by template/email preview endpoints. */
export function exampleVariableContext(
  projectName: string,
  subject: string = 'Example subject'
): VariableContext {
  return {
    contact: {
      firstname: 'Jean',
      lastname: 'Dupont',
      email: 'jean.dupont@example.com',
      phone: '+33 6 12 34 56 78',
      company: 'Acme Inc',
      country: 'France',
      city: 'Paris',
      language: 'fr',
      timezone: 'Europe/Paris',
    },
    project: { name: projectName },
    subject,
    unsubscribeUrl: '#',
  }
}
