/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  ApiKeys: () => import('#controllers/api_keys_controller'),
  api: {
    v1: {
      ContactTags: () => import('#controllers/api/v1/contact_tags_controller'),
      Contacts: () => import('#controllers/api/v1/contacts_controller'),
    },
  },
  audit: {
    AuditLog: () => import('#controllers/audit/audit_log_controller'),
  },
  campaigns: {
    CampaignBuilders: () => import('#controllers/campaigns/campaign_builders_controller'),
    CampaignVersions: () => import('#controllers/campaigns/campaign_versions_controller'),
    Campaigns: () => import('#controllers/campaigns/campaigns_controller'),
  },
  contacts: {
    ContactHistory: () => import('#controllers/contacts/contact_history_controller'),
    ContactTags: () => import('#controllers/contacts/contact_tags_controller'),
    Contacts: () => import('#controllers/contacts/contacts_controller'),
  },
  customFields: {
    CustomFieldDefinitions: () => import('#controllers/custom_fields/custom_field_definitions_controller'),
  },
  emailLayouts: {
    EmailLayouts: () => import('#controllers/email_layouts/email_layouts_controller'),
  },
  emailTemplates: {
    EmailTemplates: () => import('#controllers/email_templates/email_templates_controller'),
  },
  emails: {
    Emails: () => import('#controllers/emails/emails_controller'),
  },
  Home: () => import('#controllers/home_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  jobs: {
    FailedJobs: () => import('#controllers/jobs/failed_jobs_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  organizations: {
    OrganizationInvitations: () => import('#controllers/organizations/organization_invitations_controller'),
    OrganizationMembers: () => import('#controllers/organizations/organization_members_controller'),
    Organizations: () => import('#controllers/organizations/organizations_controller'),
  },
  projects: {
    Projects: () => import('#controllers/projects/projects_controller'),
  },
  segments: {
    SegmentPreviews: () => import('#controllers/segments/segment_previews_controller'),
    Segments: () => import('#controllers/segments/segments_controller'),
  },
  Session: () => import('#controllers/session_controller'),
  smtpConnectors: {
    SmtpConnectorTests: () => import('#controllers/smtp_connectors/smtp_connector_tests_controller'),
    SmtpConnectors: () => import('#controllers/smtp_connectors/smtp_connectors_controller'),
  },
  statistics: {
    Statistics: () => import('#controllers/statistics/statistics_controller'),
  },
  tags: {
    Tags: () => import('#controllers/tags/tags_controller'),
  },
  tracking: {
    SmtpWebhooks: () => import('#controllers/tracking/smtp_webhooks_controller'),
    Tracking: () => import('#controllers/tracking/tracking_controller'),
  },
  Unsubscribe: () => import('#controllers/unsubscribe_controller'),
}
