/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import CampaignActivated from '#events/campaign_activated'
import CampaignArchived from '#events/campaign_archived'
import CampaignCompleted from '#events/campaign_completed'
import CampaignEnrollmentCreated from '#events/campaign_enrollment_created'
import CampaignExecutionCancelled from '#events/campaign_execution_cancelled'
import CampaignExecutionCompleted from '#events/campaign_execution_completed'
import CampaignExecutionFailed from '#events/campaign_execution_failed'
import CampaignPaused from '#events/campaign_paused'
import CampaignResumed from '#events/campaign_resumed'
import CampaignVersionPublished from '#events/campaign_version_published'
import ContactCreated from '#events/contact_created'
import ContactDeleted from '#events/contact_deleted'
import ContactResubscribed from '#events/contact_resubscribed'
import ContactUnsubscribed from '#events/contact_unsubscribed'
import ContactUpdated from '#events/contact_updated'
import EmailBounced from '#events/email_bounced'
import EmailClicked from '#events/email_clicked'
import EmailComplained from '#events/email_complained'
import EmailCreated from '#events/email_created'
import EmailDeleted from '#events/email_deleted'
import EmailDelivered from '#events/email_delivered'
import EmailLayoutCreated from '#events/email_layout_created'
import EmailLayoutDeleted from '#events/email_layout_deleted'
import EmailLayoutUpdated from '#events/email_layout_updated'
import EmailOpened from '#events/email_opened'
import EmailPublished from '#events/email_published'
import EmailTemplateCreated from '#events/email_template_created'
import EmailTemplateDeleted from '#events/email_template_deleted'
import EmailTemplateUpdated from '#events/email_template_updated'
import EmailUpdated from '#events/email_updated'
import OrganizationMemberInvited from '#events/organization_member_invited'
import OrganizationMemberJoined from '#events/organization_member_joined'
import OrganizationMemberRemoved from '#events/organization_member_removed'
import OrganizationOwnershipTransferred from '#events/organization_ownership_transferred'
import ProjectCreated from '#events/project_created'
import ProjectDeleted from '#events/project_deleted'
import SegmentMembershipAdded from '#events/segment_membership_added'
import SegmentMembershipRemoved from '#events/segment_membership_removed'
import SegmentRecomputed from '#events/segment_recomputed'
import SmtpConnectorCreated from '#events/smtp_connector_created'
import SmtpConnectorDefaultChanged from '#events/smtp_connector_default_changed'
import SmtpConnectorDeleted from '#events/smtp_connector_deleted'
import SmtpConnectorUpdated from '#events/smtp_connector_updated'

export const events = {
  CampaignActivated: CampaignActivated,
  CampaignArchived: CampaignArchived,
  CampaignCompleted: CampaignCompleted,
  CampaignEnrollmentCreated: CampaignEnrollmentCreated,
  CampaignExecutionCancelled: CampaignExecutionCancelled,
  CampaignExecutionCompleted: CampaignExecutionCompleted,
  CampaignExecutionFailed: CampaignExecutionFailed,
  CampaignPaused: CampaignPaused,
  CampaignResumed: CampaignResumed,
  CampaignVersionPublished: CampaignVersionPublished,
  ContactCreated: ContactCreated,
  ContactDeleted: ContactDeleted,
  ContactResubscribed: ContactResubscribed,
  ContactUnsubscribed: ContactUnsubscribed,
  ContactUpdated: ContactUpdated,
  EmailBounced: EmailBounced,
  EmailClicked: EmailClicked,
  EmailComplained: EmailComplained,
  EmailCreated: EmailCreated,
  EmailDeleted: EmailDeleted,
  EmailDelivered: EmailDelivered,
  EmailLayoutCreated: EmailLayoutCreated,
  EmailLayoutDeleted: EmailLayoutDeleted,
  EmailLayoutUpdated: EmailLayoutUpdated,
  EmailOpened: EmailOpened,
  EmailPublished: EmailPublished,
  EmailTemplateCreated: EmailTemplateCreated,
  EmailTemplateDeleted: EmailTemplateDeleted,
  EmailTemplateUpdated: EmailTemplateUpdated,
  EmailUpdated: EmailUpdated,
  OrganizationMemberInvited: OrganizationMemberInvited,
  OrganizationMemberJoined: OrganizationMemberJoined,
  OrganizationMemberRemoved: OrganizationMemberRemoved,
  OrganizationOwnershipTransferred: OrganizationOwnershipTransferred,
  ProjectCreated: ProjectCreated,
  ProjectDeleted: ProjectDeleted,
  SegmentMembershipAdded: SegmentMembershipAdded,
  SegmentMembershipRemoved: SegmentMembershipRemoved,
  SegmentRecomputed: SegmentRecomputed,
  SmtpConnectorCreated: SmtpConnectorCreated,
  SmtpConnectorDefaultChanged: SmtpConnectorDefaultChanged,
  SmtpConnectorDeleted: SmtpConnectorDeleted,
  SmtpConnectorUpdated: SmtpConnectorUpdated,
}
