/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  EnrollContactsOnSegmentMembershipAdded: () => import('#listeners/enroll_contacts_on_segment_membership_added'),
  EnrollExistingSegmentMembersOnCampaignActivated: () => import('#listeners/enroll_existing_segment_members_on_campaign_activated'),
  RecomputeSegmentsOnContactChange: () => import('#listeners/recompute_segments_on_contact_change'),
  SendOrganizationInvitationEmail: () => import('#listeners/send_organization_invitation_email'),
  WriteAuditLog: () => import('#listeners/write_audit_log'),
}
