/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import type { SegmentDefinition } from '#types/segment_definition'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'id', 'lastUsedAt', 'name', 'projectId', 'revokedAt', 'tokenHash', 'tokenPrefix', 'updatedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare tokenHash: string
  @column()
  declare tokenPrefix: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'entityId', 'entityType', 'id', 'metadata', 'occurredAt', 'organizationId', 'projectId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare entityId: number | null
  @column()
  declare entityType: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: Record<string, unknown> | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare organizationId: number
  @column()
  declare projectId: number | null
}

export class CampaignSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'draftVersionId', 'enrollExistingMembers', 'id', 'name', 'projectId', 'publishedVersionId', 'reentryPolicy', 'status', 'updatedAt'] as const
  $columns = CampaignSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare draftVersionId: number | null
  @column()
  declare enrollExistingMembers: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column()
  declare publishedVersionId: number | null
  @column()
  declare reentryPolicy: 'never' | 'after_exit' | 'always'
  @column()
  declare status: 'draft' | 'active' | 'paused' | 'completed' | 'archived'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignDailyStatSchema extends BaseModel {
  static $columns = ['bounced', 'campaignId', 'clicked', 'createdAt', 'date', 'delivered', 'failed', 'id', 'opened', 'projectId', 'sent', 'unsubscribed', 'updatedAt'] as const
  $columns = CampaignDailyStatSchema.$columns
  @column()
  declare bounced: number
  @column()
  declare campaignId: number
  @column()
  declare clicked: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare delivered: number
  @column()
  declare failed: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare opened: number
  @column()
  declare projectId: number
  @column()
  declare sent: number
  @column()
  declare unsubscribed: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignEdgeSchema extends BaseModel {
  static $columns = ['campaignVersionId', 'createdAt', 'id', 'sourceHandle', 'sourceNodeId', 'targetNodeId'] as const
  $columns = CampaignEdgeSchema.$columns
  @column()
  declare campaignVersionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sourceHandle: string | null
  @column()
  declare sourceNodeId: number
  @column()
  declare targetNodeId: number
}

export class CampaignEnrollmentSchema extends BaseModel {
  static $columns = ['campaignId', 'campaignVersionId', 'contactId', 'createdAt', 'enrolledAt', 'exitReason', 'exitedAt', 'id', 'projectId', 'source', 'status', 'updatedAt'] as const
  $columns = CampaignEnrollmentSchema.$columns
  @column()
  declare campaignId: number
  @column()
  declare campaignVersionId: number
  @column()
  declare contactId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare enrolledAt: DateTime
  @column()
  declare exitReason: string | null
  @column.dateTime()
  declare exitedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare source: string
  @column()
  declare status: 'active' | 'completed' | 'exited' | 'cancelled'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignExecutionSchema extends BaseModel {
  static $columns = ['attemptCount', 'campaignEnrollmentId', 'createdAt', 'currentNodeId', 'finishedAt', 'id', 'lastError', 'lockVersion', 'lockedAt', 'lockedBy', 'scheduledAt', 'startedAt', 'status', 'updatedAt'] as const
  $columns = CampaignExecutionSchema.$columns
  @column()
  declare attemptCount: number
  @column()
  declare campaignEnrollmentId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentNodeId: number | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastError: string | null
  @column()
  declare lockVersion: number
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column()
  declare lockedBy: string | null
  @column.dateTime()
  declare scheduledAt: DateTime
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: 'pending' | 'running' | 'waiting' | 'completed' | 'failed' | 'cancelled'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignExecutionEventSchema extends BaseModel {
  static $columns = ['campaignExecutionId', 'id', 'message', 'metadata', 'nodeId', 'occurredAt', 'type'] as const
  $columns = CampaignExecutionEventSchema.$columns
  @column()
  declare campaignExecutionId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare metadata: Record<string, unknown> | null
  @column()
  declare nodeId: number | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare type: string
}

export class CampaignNodeSchema extends BaseModel {
  static $columns = ['campaignVersionId', 'clientKey', 'config', 'createdAt', 'id', 'positionX', 'positionY', 'subtype', 'type', 'updatedAt'] as const
  $columns = CampaignNodeSchema.$columns
  @column()
  declare campaignVersionId: number
  @column()
  declare clientKey: string
  @column()
  declare config: Record<string, unknown>
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare positionX: number
  @column()
  declare positionY: number
  @column()
  declare subtype: string
  @column()
  declare type: 'source' | 'action' | 'condition' | 'trigger'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CampaignVersionSchema extends BaseModel {
  static $columns = ['campaignId', 'createdAt', 'createdByUserId', 'graphFormatVersion', 'id', 'publishedAt', 'status', 'updatedAt', 'versionNumber'] as const
  $columns = CampaignVersionSchema.$columns
  @column()
  declare campaignId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare graphFormatVersion: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare status: 'draft' | 'published' | 'archived'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare versionNumber: number
}

export class ContactSchema extends BaseModel {
  static $columns = ['city', 'company', 'country', 'createdAt', 'customFields', 'deletedAt', 'email', 'firstName', 'id', 'language', 'lastName', 'phone', 'projectId', 'status', 'timezone', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column()
  declare city: string | null
  @column()
  declare company: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customFields: Record<string, string | number | boolean | null> | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare language: string | null
  @column()
  declare lastName: string | null
  @column()
  declare phone: string | null
  @column()
  declare projectId: number
  @column()
  declare status: 'subscribed' | 'unsubscribed' | 'bounced' | 'complained' | 'blocked'
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactTagSchema extends BaseModel {
  static $columns = ['contactId', 'createdAt', 'id', 'tagId'] as const
  $columns = ContactTagSchema.$columns
  @column()
  declare contactId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tagId: number
}

export class ContactUnsubscribeEventSchema extends BaseModel {
  static $columns = ['campaignId', 'contactId', 'id', 'occurredAt', 'projectId', 'reason', 'source'] as const
  $columns = ContactUnsubscribeEventSchema.$columns
  @column()
  declare campaignId: number | null
  @column()
  declare contactId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare projectId: number
  @column()
  declare reason: string | null
  @column()
  declare source: 'link' | 'manual' | 'bounce' | 'complaint' | 'api'
}

export class CustomFieldDefinitionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'label', 'projectId', 'type', 'updatedAt'] as const
  $columns = CustomFieldDefinitionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare projectId: number
  @column()
  declare type: 'text' | 'number' | 'boolean' | 'date'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailSchema extends BaseModel {
  static $columns = ['bodyContent', 'createdAt', 'emailLayoutId', 'emailTemplateId', 'htmlContent', 'id', 'name', 'preheader', 'projectId', 'replyTo', 'senderEmail', 'senderName', 'status', 'subject', 'textContent', 'updatedAt'] as const
  $columns = EmailSchema.$columns
  @column()
  declare bodyContent: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare emailLayoutId: number | null
  @column()
  declare emailTemplateId: number | null
  @column()
  declare htmlContent: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare preheader: string | null
  @column()
  declare projectId: number
  @column()
  declare replyTo: string | null
  @column()
  declare senderEmail: string
  @column()
  declare senderName: string
  @column()
  declare status: 'draft' | 'published'
  @column()
  declare subject: string
  @column()
  declare textContent: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailDeliverySchema extends BaseModel {
  static $columns = ['attemptCount', 'campaignExecutionId', 'campaignId', 'contactId', 'createdAt', 'deliveredAt', 'emailId', 'id', 'idempotencyKey', 'lastError', 'projectId', 'providerMessageId', 'sentAt', 'smtpConnectorId', 'status', 'updatedAt'] as const
  $columns = EmailDeliverySchema.$columns
  @column()
  declare attemptCount: number
  @column()
  declare campaignExecutionId: number | null
  @column()
  declare campaignId: number | null
  @column()
  declare contactId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare emailId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idempotencyKey: string
  @column()
  declare lastError: string | null
  @column()
  declare projectId: number
  @column()
  declare providerMessageId: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare smtpConnectorId: number | null
  @column()
  declare status: 'pending' | 'queued' | 'processing' | 'sent' | 'delivered' | 'failed' | 'bounced'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailEventSchema extends BaseModel {
  static $columns = ['contactId', 'emailDeliveryId', 'id', 'metadata', 'occurredAt', 'projectId', 'type'] as const
  $columns = EmailEventSchema.$columns
  @column()
  declare contactId: number
  @column()
  declare emailDeliveryId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: Record<string, unknown> | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare projectId: number
  @column()
  declare type: 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'complained' | 'failed' | 'unsubscribed'
}

export class EmailLayoutSchema extends BaseModel {
  static $columns = ['createdAt', 'htmlContent', 'id', 'name', 'projectId', 'textContent', 'updatedAt'] as const
  $columns = EmailLayoutSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare htmlContent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column()
  declare textContent: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'htmlContent', 'id', 'name', 'projectId', 'subject', 'textContent', 'updatedAt'] as const
  $columns = EmailTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare htmlContent: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column()
  declare subject: string
  @column()
  declare textContent: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'imagePath', 'name', 'ownerUserId', 'slug', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare ownerUserId: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationInvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'invitedByUserId', 'organizationId', 'revokedAt', 'role', 'token', 'updatedAt'] as const
  $columns = OrganizationInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number
  @column()
  declare organizationId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: 'owner' | 'admin' | 'member' | 'viewer'
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationMembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'invitedByUserId', 'joinedAt', 'organizationId', 'role', 'updatedAt', 'userId'] as const
  $columns = OrganizationMembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserId: number | null
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare organizationId: number
  @column()
  declare role: 'owner' | 'admin' | 'member' | 'viewer'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultSenderEmail', 'defaultSenderName', 'id', 'imagePath', 'name', 'organizationId', 'settings', 'slug', 'timezone', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultSenderEmail: string | null
  @column()
  declare defaultSenderName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string | null
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare settings: Record<string, unknown>
  @column()
  declare slug: string
  @column()
  declare timezone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectDailyStatSchema extends BaseModel {
  static $columns = ['contactsActive', 'contactsTotal', 'createdAt', 'date', 'emailsBounced', 'emailsClicked', 'emailsDelivered', 'emailsFailed', 'emailsOpened', 'emailsSent', 'id', 'projectId', 'unsubscribes', 'updatedAt'] as const
  $columns = ProjectDailyStatSchema.$columns
  @column()
  declare contactsActive: number
  @column()
  declare contactsTotal: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare date: DateTime
  @column()
  declare emailsBounced: number
  @column()
  declare emailsClicked: number
  @column()
  declare emailsDelivered: number
  @column()
  declare emailsFailed: number
  @column()
  declare emailsOpened: number
  @column()
  declare emailsSent: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare unsubscribes: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SegmentSchema extends BaseModel {
  static $columns = ['contactCountCache', 'createdAt', 'definition', 'description', 'id', 'lastComputationStatus', 'lastComputedAt', 'name', 'projectId', 'referencedFields', 'updatedAt'] as const
  $columns = SegmentSchema.$columns
  @column()
  declare contactCountCache: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare definition: SegmentDefinition
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastComputationStatus: 'idle' | 'running' | 'success' | 'failed'
  @column.dateTime()
  declare lastComputedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column()
  declare referencedFields: string[]
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SegmentContactSchema extends BaseModel {
  static $columns = ['addedAt', 'contactId', 'id', 'segmentId'] as const
  $columns = SegmentContactSchema.$columns
  @column.dateTime()
  declare addedAt: DateTime
  @column()
  declare contactId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare segmentId: number
}

export class SmtpConnectorSchema extends BaseModel {
  static $columns = ['createdAt', 'dailyLimit', 'enabled', 'encryption', 'fromEmail', 'fromName', 'host', 'id', 'isDefault', 'lastTestStatus', 'lastTestedAt', 'name', 'passwordEncrypted', 'port', 'projectId', 'replyTo', 'updatedAt', 'username'] as const
  $columns = SmtpConnectorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyLimit: number | null
  @column()
  declare enabled: boolean
  @column()
  declare encryption: 'none' | 'ssl' | 'tls'
  @column()
  declare fromEmail: string
  @column()
  declare fromName: string
  @column()
  declare host: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare lastTestStatus: 'unknown' | 'success' | 'failed'
  @column.dateTime()
  declare lastTestedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare passwordEncrypted: string
  @column()
  declare port: number
  @column()
  declare projectId: number
  @column()
  declare replyTo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class TagSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'projectId', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UnsubscribeTokenSchema extends BaseModel {
  static $columns = ['contactId', 'createdAt', 'id', 'projectId', 'token', 'usedAt'] as const
  $columns = UnsubscribeTokenSchema.$columns
  @column()
  declare contactId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare token: string
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
