/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type ApiKeyTransformer from '#transformers/api_key_transformer'
import type AuditLogTransformer from '#transformers/audit_log_transformer'
import type CampaignGraphTransformer from '#transformers/campaign_graph_transformer'
import type CampaignTransformer from '#transformers/campaign_transformer'
import type CampaignVersionTransformer from '#transformers/campaign_version_transformer'
import type ContactTransformer from '#transformers/contact_transformer'
import type CustomFieldDefinitionTransformer from '#transformers/custom_field_definition_transformer'
import type EmailLayoutTransformer from '#transformers/email_layout_transformer'
import type EmailTemplateTransformer from '#transformers/email_template_transformer'
import type EmailTransformer from '#transformers/email_transformer'
import type OrganizationInvitationTransformer from '#transformers/organization_invitation_transformer'
import type OrganizationMembershipTransformer from '#transformers/organization_membership_transformer'
import type OrganizationTransformer from '#transformers/organization_transformer'
import type ProjectTransformer from '#transformers/project_transformer'
import type SegmentTransformer from '#transformers/segment_transformer'
import type SmtpConnectorTransformer from '#transformers/smtp_connector_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ApiKey = InferData<ApiKeyTransformer>
  export namespace ApiKey {
    export type Variants = InferVariants<ApiKeyTransformer>
  }
  export type AuditLog = InferData<AuditLogTransformer>
  export namespace AuditLog {
    export type Variants = InferVariants<AuditLogTransformer>
  }
  export type CampaignGraph = InferData<CampaignGraphTransformer>
  export namespace CampaignGraph {
    export type Variants = InferVariants<CampaignGraphTransformer>
  }
  export type Campaign = InferData<CampaignTransformer>
  export namespace Campaign {
    export type Variants = InferVariants<CampaignTransformer>
  }
  export type CampaignVersion = InferData<CampaignVersionTransformer>
  export namespace CampaignVersion {
    export type Variants = InferVariants<CampaignVersionTransformer>
  }
  export type Contact = InferData<ContactTransformer>
  export namespace Contact {
    export type Variants = InferVariants<ContactTransformer>
  }
  export type CustomFieldDefinition = InferData<CustomFieldDefinitionTransformer>
  export namespace CustomFieldDefinition {
    export type Variants = InferVariants<CustomFieldDefinitionTransformer>
  }
  export type EmailLayout = InferData<EmailLayoutTransformer>
  export namespace EmailLayout {
    export type Variants = InferVariants<EmailLayoutTransformer>
  }
  export type EmailTemplate = InferData<EmailTemplateTransformer>
  export namespace EmailTemplate {
    export type Variants = InferVariants<EmailTemplateTransformer>
  }
  export type Email = InferData<EmailTransformer>
  export namespace Email {
    export type Variants = InferVariants<EmailTransformer>
  }
  export type OrganizationInvitation = InferData<OrganizationInvitationTransformer>
  export namespace OrganizationInvitation {
    export type Variants = InferVariants<OrganizationInvitationTransformer>
  }
  export type OrganizationMembership = InferData<OrganizationMembershipTransformer>
  export namespace OrganizationMembership {
    export type Variants = InferVariants<OrganizationMembershipTransformer>
  }
  export type Organization = InferData<OrganizationTransformer>
  export namespace Organization {
    export type Variants = InferVariants<OrganizationTransformer>
  }
  export type Project = InferData<ProjectTransformer>
  export namespace Project {
    export type Variants = InferVariants<ProjectTransformer>
  }
  export type Segment = InferData<SegmentTransformer>
  export namespace Segment {
    export type Variants = InferVariants<SegmentTransformer>
  }
  export type SmtpConnector = InferData<SmtpConnectorTransformer>
  export namespace SmtpConnector {
    export type Variants = InferVariants<SmtpConnectorTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
